services:
  device_app:
    container_name: device_app
    build:
      context: ..
      dockerfile: Infra/docker/devices.Dockerfile
    volumes:
      - ../Apps/device_app:/app
      - ./docker/air/device.air.toml:/app/.air.toml
    working_dir: /app
    tty: true
    environment:
      - ENV=development