version: '3.8'

services:
  devices:
    container_name: devices
    build:
      context: ..
      dockerfile: Infra/docker/devices.Dockerfile
    volumes:
      - ../Apps/device_app:/app
      - ./docker/air/device.air.toml:/app/.air.toml
      
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - ENV=development

    command: air -c .air.toml
    tty: true